
<h1><center>Практическая работа №1</center></h1>

<h3><center>Разведочный анализ</center></h3>

<p>Цель работы: провести разведочный анализ данных по датасету.</p>

Задание на практическую работу:

<h3>На 3:</h3>

<ul>
    <li>Загрузка датасета;</li>
    <li>Просмотр и исследование датасета;</li>
    <li>Обработка датасета:
        <ul>
            <li>Удаление хотя бы одного признака;</li>
            <li>Замена и удаление значений;</li>
            <li>Отсортировать значения в датафрейме по указанному столбцу;</li>
            <li>Убрать дубликаты в датафрейме;</li>
        </ul>
    </li>
    <li>Выбрать один признак (категориальный) в качестве целевой переменной и обосновать данный выбор;</li>
    <li>Написать заключение по проведенному исследованию;</li>
    <li>Сохранить датасет.</li>
</ul>

<h3>На 4:</h3>

<ul>
    <li>На основе собственного выбранного датасета проведен разведочный анализ со всеми этапами.</li>
    <li>Отчет оформлен малоинформативно или не информативно.</li>
</ul>

<h3>На 5:</h3>

<ul>
    <li>На основе собственного выбранного датасета проведен разведочный анализ со всеми этапами.</li>
    <li>Отчет оформлен информативно и полно.</li>
</ul>

<h2>Основные понятия</h2>
<ul>
    <li><b>Разведочный анализ данных (EDA)</b> — проводится для того, чтобы понять, что исследуется, зачем это и как оно нам пригодится.</li>
    <li><b>Dataset</b> — это набор исследуемых данных.</li>
    <li><b>Признак</b> — исходные данные, которые подаются алгоритму ML, обозначается <b>X</b>.</li>
    <li><b>Категориальный признак</b> — признак с ограниченным числом значений.</li>
    <li><b>Метка</b> — это желаемый результат, обозначается <b>Y</b>.</li>
    <li><b>Целевая переменная</b> — это прогнозируемый признак датасета.</li>
    <li><b>Разреженность данных</b> — сколько в данных пустых значений (пропусков).</li>
    <li><b>Дубликаты</b> — повторяющаяся информация. Удаляются, так как повторяются и заполняют датасет лишним.</li>
    <li><b>Pandas</b> — Python-библиотека для работы с данными.</li>
    <li><b>NumPy</b> — Python-библиотека, которая тоже позволяет работать с данными (массивы и вычисления над ними).</li>
</ul>

<h2>Описание датасета</h2>
<p>Это датасет о статистике матчей VCT (Valorant Champions Tour) по игре <a href="https://playvalorant.com/">Valorant</a>.</p>
<p>Источник: <a href="https://www.kaggle.com/datasets/ryanluong1/valorant-champion-tour-2021-2023-data">Kaggle — Valorant Champion Tour Data</a></p>
<p>Здесь описаны такие данные как:</p>
<ul>
    <li>идентификаторы (ID) турниров, стадий, матчей, игр, команд и игроков;</li>
    <li>сокращённые названия (теги) команд;</li>
    <li>пикрейты агентов и выбор агентов командами;</li>
    <li>статистика карт: сколько раз сыграна, процент побед за атаку и защиту;</li>
    <li>драфт карт — баны и пики;</li>
    <li>экономика раундов: стоимость снаряжения, остаток кредитов, тип закупки;</li>
    <li>дуэли игроков, мультикиллы (2k–5k) и клатчи (1v1–1v5);</li>
    <li>счёт на картах и в матчах, длительность карт;</li>
    <li>способы выигрыша и проигрыша раундов;</li>
    <li>статистика игроков: рейтинг, ACS, убийства, смерти, ассисты, KAST, ADR, процент хедшотов, первые убийства.</li>
</ul>
<p><b>Личная цель:</b> понять, почему FNATIC дошли до гранд-финалов обоих международных турниров 2025 года (Masters Toronto и Champions), но проиграли оба.</p>
<p>Для исследования взят сезон <b>VCT 2025</b>. Из него выбраны только те файлы, которые нужны для ответа на личную цель:</p>
<p>| Файл | Зачем нужен |</p>
<p>|---|---|</p>
<p>| <code>scores.csv</code> | результаты всех матчей: путь FNATIC по сетке и гранд-финалы |</p>
<p>| <code>draft_phase.csv</code> | баны и пики карт перед матчем |</p>
<p>| <code>maps_scores.csv</code> | счёт на каждой карте: на каких картах FNATIC выигрывают и проигрывают |</p>
<p>| <code>overview.csv</code> | статистика игроков на картах: как FNATIC сыграли в финалах по сравнению с сезоном |</p>
<p>| <code>win_loss_methods_round_number.csv</code> | исход и способ окончания каждого раунда |</p>
<p>| <code>eco_rounds.csv</code> | экономика раундов: как команда играла на разных закупках |</p>
<p><b>Ошибка в исходных данных:</b> в сезоне 2025 во всех матчах команды NRG она записана как <code>Mega Minors</code> (например, в матче <code>NRG vs FNATIC</code> в столбце команды стоит <code>Mega Minors</code>). Поэтому в каждом файле заменяем <code>Mega Minors</code> на <code>NRG</code>.</p>

<h2>Используемые команды</h2>
<ul>
    <li><code>pd.read_csv(path)</code> — загружает CSV-файл в DataFrame;</li>
    <li><code>df.info()</code> — показывает столбцы, их типы и количество непустых значений;</li>
    <li><code>df.head()</code> — выводит первые 5 строк;</li>
    <li><code>df.shape</code> — размер таблицы (строки, столбцы); <code>df.shape[0]</code> — число строк, <code>df.shape[1]</code> — число столбцов;</li>
    <li><code>df.describe()</code> — описательная статистика числовых столбцов (среднее, минимум, максимум и т.д.);</li>
    <li><code>df.isnull().sum()</code> — количество пропусков в каждом столбце;</li>
    <li><code>df.drop('столбец', axis = 1)</code> — удаляет столбец (признак);</li>
    <li><code>df.replace(старое, новое)</code> — заменяет значения;</li>
    <li><code>df.fillna(значение)</code> — заменяет пропуски на значение;</li>
    <li><code>df.dropna()</code> — удаляет строки с пропусками;</li>
    <li><code>str.replace()</code> — заменяет часть строки (например, убирает знак <code>%</code>);</li>
    <li><code>df.sort_values(by = 'столбец')</code> — сортирует таблицу по столбцу;</li>
    <li><code>df.drop_duplicates()</code> — удаляет повторяющиеся строки;</li>
    <li><code>df.to_csv('файл.csv')</code> — сохраняет таблицу в CSV-файл;</li>
    <li><code>df[условие]</code> — выбирает строки по условию (например, только матчи FNATIC);</li>
    <li><code>df.groupby('столбец')</code> — группирует строки, чтобы посчитать итоги по группам.</li>
</ul>

Для работы нам необходимы следующие библиотеки

In [1]:
import pandas as pd
import numpy as np

<h1>Целевая переменная</h1>
<p>В качестве целевой переменной выбран категориальный признак <b><code>Team</code></b> (команда).</p>
<p>Почему именно он:</p>
<ul>
    <li>команда есть во всех выбранных файлах (в <code>scores.csv</code> и <code>maps_scores.csv</code> как <code>Team A</code>/<code>Team B</code>), поэтому через неё связываются все данные: матчи, драфт, карты, игроки, раунды;</li>
    <li>признак категориальный, в сезоне 2025 всего 58 команд;</li>
    <li>личная цель — про одну команду, FNATIC, поэтому выборки для неё делаются по этому признаку.</li>
</ul>

<h1>Разведочный анализ</h1>

<h2>Файл: scores.csv — матчи FNATIC и путь к финалам</h2>
<p>Итоговый счёт матчей.</p>
<ul>
    <li><code>Tournament</code>, <code>Stage</code>, <code>Match Type</code>, <code>Match Name</code> — турнир, стадия, тип матча (раунд сетки), матч;</li>
    <li><code>Team A</code>, <code>Team B</code> — команды;</li>
    <li><code>Team A Score</code>, <code>Team B Score</code> — выигранные карты;</li>
    <li><code>Match Result</code> — победитель матча.</li>
</ul>

In [2]:
path = '../datasets/archive/vct_2025/matches/scores.csv'
df = pd.read_csv(path)
df.info()
display(df.head())
print(df.shape)
print(df.shape[0]) # 0 - это строки
print(df.shape[1]) # 1 - это столбцы
display(df.describe())
display(df.isnull().sum())
print('Дубликатов:', df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tournament    503 non-null    str
 1   Stage         503 non-null    str
 2   Match Type    503 non-null    str
 3   Match Name    503 non-null    str
 4   Team A        503 non-null    str
 5   Team B        503 non-null    str
 6   Team A Score  503 non-null    int64
 7   Team B Score  503 non-null    int64
 8   Match Result  503 non-null    str
dtypes: int64(2), str(7)
memory usage: 86.1 KB

,Tournament,Stage,Match Type,Match Name,Team A,Team B,Team A Score,Team B Score,Match Result
0,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Paper Rex,Xi Lai Gaming,2,0,Paper Rex won
1,Valorant Champions 2025,Group Stage,Opening (A),GIANTX vs Sentinels,GIANTX,Sentinels,2,1,GIANTX won
2,Valorant Champions 2025,Group Stage,Opening (C),NRG vs EDward Gaming,Mega Minors,EDward Gaming,2,0,NRG won
3,Valorant Champions 2025,Group Stage,Opening (C),Team Liquid vs DRX,Team Liquid,DRX,0,2,DRX won
4,Valorant Champions 2025,Group Stage,Opening (D),Dragon Ranger Gaming vs T1,Dragon Ranger Gaming,T1,0,2,T1 won

(503, 9)
503
9

       Team A Score  Team B Score
count    503.000000    503.000000
mean       1.395626      1.337972
std        1.292231      1.293983
min        0.000000      0.000000
25%        0.000000      0.000000
50%        2.000000      1.000000
75%        2.000000      2.000000
max       13.000000     13.000000

Tournament      0
Stage           0
Match Type      0
Match Name      0
Team A          0
Team B          0
Team A Score    0
Team B Score    0
Match Result    0
dtype: int64

Дубликатов: 0

In [3]:
df = df.replace('Mega Minors', 'NRG') # ошибка в исходных данных: NRG записана как Mega Minors
df['Match Result'] = df['Match Result'].str.replace(' won', '') # 'FNATIC won' -> 'FNATIC'
df = df.sort_values(by = 'Tournament')
df = df.drop_duplicates()
display(df.head())
print(df.shape)
df.to_csv('../datasets/processed/scores.csv')

,Tournament,Stage,Match Type,Match Name,Team A,Team B,Team A Score,Team B Score,Match Result
459,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,Evil Geniuses vs LOUD,Evil Geniuses,LOUD,0,2,LOUD
460,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,MIBR vs 100 Thieves,MIBR,100 Thieves,0,2,100 Thieves
461,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,2Game Esports vs FURIA,2Game Esports,FURIA,0,2,FURIA
462,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,NRG vs Cloud9,NRG,Cloud9,0,2,Cloud9
463,VCT 2025: Americas Kickoff,Main Event,Upper Quarterfinals,KRÜ Esports vs LOUD,KRÜ Esports,LOUD,0,2,LOUD

(503, 9)

<p>Матчи FNATIC за сезон и гранд-финалы</p>

In [4]:
fnatic = df[(df['Team A'] == 'FNATIC') | (df['Team B'] == 'FNATIC')]
print('Матчей:', fnatic.shape[0])
print('Побед:', (fnatic['Match Result'] == 'FNATIC').sum())
finals = fnatic[fnatic['Match Type'] == 'Grand Final']
display(finals[['Tournament', 'Match Name', 'Team A Score', 'Team B Score', 'Match Result']])

Матчей: 34
Побед: 24

,Tournament,Match Name,Team A Score,Team B Score,Match Result
271,VCT 2025: EMEA Stage 1,FNATIC vs Team Heretics,3,0,FNATIC
33,Valorant Champions 2025,NRG vs FNATIC,3,2,NRG
229,Valorant Masters Toronto 2025,Paper Rex vs FNATIC,3,1,Paper Rex

<p>Путь FNATIC к финалам (плей-офф)</p>

In [5]:
lost = ['Valorant Masters Toronto 2025', 'Valorant Champions 2025']
won = ['VCT 2025: EMEA Stage 1']
path_to_final = fnatic[fnatic['Tournament'].isin(lost + won) & (fnatic['Stage'] == 'Playoffs')]
display(path_to_final[['Tournament', 'Match Type', 'Match Name', 'Team A Score', 'Team B Score', 'Match Result']])

,Tournament,Match Type,Match Name,Team A Score,Team B Score,Match Result
261,VCT 2025: EMEA Stage 1,Upper Round 1,FNATIC vs FUT Esports,2,0,FNATIC
265,VCT 2025: EMEA Stage 1,Upper Semifinals,Team Liquid vs FNATIC,1,2,FNATIC
268,VCT 2025: EMEA Stage 1,Upper Final,Team Heretics vs FNATIC,0,2,FNATIC
271,VCT 2025: EMEA Stage 1,Grand Final,FNATIC vs Team Heretics,3,0,FNATIC
21,Valorant Champions 2025,Upper Quarterfinals,FNATIC vs DRX,2,1,FNATIC
26,Valorant Champions 2025,Upper Semifinals,FNATIC vs Paper Rex,2,1,FNATIC
30,Valorant Champions 2025,Upper Final,FNATIC vs NRG,0,2,NRG
32,Valorant Champions 2025,Lower Final,FNATIC vs DRX,3,1,FNATIC
33,Valorant Champions 2025,Grand Final,NRG vs FNATIC,3,2,NRG
219,Valorant Masters Toronto 2025,Upper Quarterfinals,FNATIC vs Gen.G,1,2,Gen.G
221,Valorant Masters Toronto 2025,Lower Round 1,Rex Regum Qeon vs FNATIC,1,2,FNATIC
225,Valorant Masters Toronto 2025,Lower Round 2,Sentinels vs FNATIC,1,2,FNATIC
227,Valorant Masters Toronto 2025,Lower Round 3,G2 Esports vs FNATIC,0,2,FNATIC
228,Valorant Masters Toronto 2025,Lower Final,Wolves Esports vs FNATIC,1,3,FNATIC
229,Valorant Masters Toronto 2025,Grand Final,Paper Rex vs FNATIC,3,1,Paper Rex

<p><b>Ответ:</b></p>
<ul>
    <li>За сезон у FNATIC сильный показатель: 24 победы в 34 матчах.</li>
    <li>В EMEA Stage 1 путь к финалу был намного проще.</li>
    <li>В проигранных финалах FNATIC шли через нижнюю сетку и сыграли больше матчей.</li>
</ul>

<h2>Файл: draft_phase.csv — драфты FNATIC</h2>
<p>Драфт карт перед матчем.</p>
<ul>
    <li><code>Tournament</code>, <code>Stage</code>, <code>Match Type</code>, <code>Match Name</code> — турнир, стадия, тип матча, матч;</li>
    <li><code>Team</code> — команда, которая делает выбор;</li>
    <li><code>Action</code> — действие: <code>ban</code> (запрет карты) или <code>pick</code> (выбор карты);</li>
    <li><code>Map</code> — карта.</li>
</ul>

In [6]:
path = '../datasets/archive/vct_2025/matches/draft_phase.csv'
df = pd.read_csv(path)
df.info()
display(df.head())
print(df.shape)
print(df.shape[0]) # 0 - это строки
print(df.shape[1]) # 1 - это столбцы
display(df.describe())
display(df.isnull().sum())
print('Дубликатов:', df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 2988 entries, 0 to 2987
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  2988 non-null   str
 1   Stage       2988 non-null   str
 2   Match Type  2988 non-null   str
 3   Match Name  2988 non-null   str
 4   Team        2988 non-null   str
 5   Action      2988 non-null   str
 6   Map         2988 non-null   str
dtypes: str(7)
memory usage: 419.1 KB

,Tournament,Stage,Match Type,Match Name,Team,Action,Map
0,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Xi Lai Gaming,ban,Lotus
1,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Paper Rex,ban,Abyss
2,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Xi Lai Gaming,pick,Bind
3,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Paper Rex,pick,Sunset
4,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Xi Lai Gaming,ban,Corrode

(2988, 7)
2988
7

,Tournament,Stage,Match Type,Match Name,Team,Action,Map
count,2988,2988,2988,2988,2988,2988,2988
unique,15,4,36,355,48,2,11
top,VCT 2025: Americas Stage 2,Group Stage,Week 1,Sentinels vs G2 Esports,G2 Esports,ban,Lotus
freq,252,1560,324,24,116,1932,427

Tournament    0
Stage         0
Match Type    0
Match Name    0
Team          0
Action        0
Map           0
dtype: int64

Дубликатов: 0

In [7]:
df = df.replace('Mega Minors', 'NRG') # ошибка в исходных данных: NRG записана как Mega Minors
df.drop('Stage', axis = 1, inplace = True) # удаляем признак: для драфта стадия не нужна, есть Match Type
df = df.sort_values(by = 'Match Name')
df = df.drop_duplicates()
display(df.head())
print(df.shape)
df.to_csv('../datasets/processed/draft_phase.csv')

,Tournament,Match Type,Match Name,Team,Action,Map
2220,VCT 2025: Americas Stage 1,Week 4,100 Thieves vs 2Game Esports,2Game Esports,ban,Fracture
2221,VCT 2025: Americas Stage 1,Week 4,100 Thieves vs 2Game Esports,100 Thieves,ban,Lotus
2222,VCT 2025: Americas Stage 1,Week 4,100 Thieves vs 2Game Esports,2Game Esports,pick,Ascent
2223,VCT 2025: Americas Stage 1,Week 4,100 Thieves vs 2Game Esports,100 Thieves,pick,Icebox
2224,VCT 2025: Americas Stage 1,Week 4,100 Thieves vs 2Game Esports,2Game Esports,ban,Haven

(2988, 6)

<p>Драфт карт в гранд-финалах FNATIC</p>

In [8]:
gf_draft = df[(df['Match Type'] == 'Grand Final') & df['Tournament'].isin(lost + won) & df['Match Name'].str.contains('FNATIC')]
display(gf_draft[['Tournament', 'Match Name', 'Team', 'Action', 'Map']])

,Tournament,Match Name,Team,Action,Map
1602,VCT 2025: EMEA Stage 1,FNATIC vs Team Heretics,FNATIC,ban,Pearl
1603,VCT 2025: EMEA Stage 1,FNATIC vs Team Heretics,FNATIC,ban,Haven
1604,VCT 2025: EMEA Stage 1,FNATIC vs Team Heretics,FNATIC,pick,Split
1605,VCT 2025: EMEA Stage 1,FNATIC vs Team Heretics,Team Heretics,pick,Icebox
1606,VCT 2025: EMEA Stage 1,FNATIC vs Team Heretics,FNATIC,pick,Fracture
1607,VCT 2025: EMEA Stage 1,FNATIC vs Team Heretics,Team Heretics,pick,Lotus
198,Valorant Champions 2025,NRG vs FNATIC,NRG,ban,Haven
199,Valorant Champions 2025,NRG vs FNATIC,NRG,ban,Bind
200,Valorant Champions 2025,NRG vs FNATIC,NRG,pick,Corrode
201,Valorant Champions 2025,NRG vs FNATIC,FNATIC,pick,Lotus
202,Valorant Champions 2025,NRG vs FNATIC,NRG,pick,Abyss
203,Valorant Champions 2025,NRG vs FNATIC,FNATIC,pick,Ascent
1350,Valorant Masters Toronto 2025,Paper Rex vs FNATIC,Paper Rex,ban,Haven
1351,Valorant Masters Toronto 2025,Paper Rex vs FNATIC,Paper Rex,ban,Ascent
1352,Valorant Masters Toronto 2025,Paper Rex vs FNATIC,Paper Rex,pick,Sunset
1353,Valorant Masters Toronto 2025,Paper Rex vs FNATIC,FNATIC,pick,Icebox
1354,Valorant Masters Toronto 2025,Paper Rex vs FNATIC,Paper Rex,pick,Pearl
1355,Valorant Masters Toronto 2025,Paper Rex vs FNATIC,FNATIC,pick,Lotus

<p><b>Ответ:</b></p>
<ul>
    <li>FNATIC не могли забанить Sunset, которую за сезон сыграли 6 раз и ни разу не выиграли: в гранд-финале Bo5 два бана получает команда из верхней сетки, а FNATIC оба раза пришли из нижней.</li>
    <li>Из-за более ограниченного пула карт FNATIC были в худшей позиции: не могли отдать сопернику более сильную для него карту, а сами брали не самую сильную свою.</li>
</ul>

<h2>Файл: maps_scores.csv — карты FNATIC</h2>
<p>Счёт на каждой карте.</p>
<ul>
    <li><code>Tournament</code>, <code>Stage</code>, <code>Match Type</code>, <code>Match Name</code>, <code>Map</code> — турнир, стадия, тип матча, матч, карта;</li>
    <li><code>Team A</code>, <code>Team B</code> — команды;</li>
    <li><code>Team A Score</code>, <code>Team B Score</code> — раунды, выигранные командой;</li>
    <li><code>... Attacker Score</code>, <code>... Defender Score</code> — раунды, выигранные за атаку и за защиту;</li>
    <li><code>... Overtime Score</code> — раунды, выигранные в овертайме;</li>
    <li><code>Duration</code> — длительность карты.</li>
</ul>

In [9]:
path = '../datasets/archive/vct_2025/matches/maps_scores.csv'
df = pd.read_csv(path)
df.info()
display(df.head())
print(df.shape)
print(df.shape[0]) # 0 - это строки
print(df.shape[1]) # 1 - это столбцы
display(df.describe())
display(df.isnull().sum())
print('Дубликатов:', df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tournament             1277 non-null   str
 1   Stage                  1277 non-null   str
 2   Match Type             1277 non-null   str
 3   Match Name             1277 non-null   str
 4   Map                    1277 non-null   str
 5   Team A                 1277 non-null   str
 6   Team A Score           1277 non-null   int64
 7   Team A Attacker Score  1277 non-null   int64
 8   Team A Defender Score  1277 non-null   int64
 9   Team A Overtime Score  145 non-null    float64
 10  Team B                 1277 non-null   str
 11  Team B Score           1277 non-null   int64
 12  Team B Attacker Score  1277 non-null   int64
 13  Team B Defender Score  1277 non-null   int64
 14  Team B Overtime Score  145 non-null    float64
 15  Duration               1179 non-null   str
dtypes: float64(2), int64(6), str(8)
memory usage: 283.8 KB

,Tournament,Stage,Match Type,Match Name,Map,Team A,Team A Score,Team A Attacker Score,Team A Defender Score,Team A Overtime Score,Team B,Team B Score,Team B Attacker Score,Team B Defender Score,Team B Overtime Score,Duration
0,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,Paper Rex,13,6,7,NaN,Xi Lai Gaming,9,3,6,NaN,48:56
1,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Sunset,Paper Rex,13,8,5,NaN,Xi Lai Gaming,5,1,4,NaN,39:04
2,Valorant Champions 2025,Group Stage,Opening (A),GIANTX vs Sentinels,Corrode,GIANTX,6,6,0,NaN,Sentinels,13,7,6,NaN,41:17
3,Valorant Champions 2025,Group Stage,Opening (A),GIANTX vs Sentinels,Sunset,GIANTX,13,10,3,NaN,Sentinels,4,2,2,NaN,38:15
4,Valorant Champions 2025,Group Stage,Opening (A),GIANTX vs Sentinels,Haven,GIANTX,13,4,9,NaN,Sentinels,9,1,8,NaN,51:34

(1277, 16)
1277
16

,Team A Score,Team A Attacker Score,Team A Defender Score,Team A Overtime Score,Team B Score,Team B Attacker Score,Team B Defender Score,Team B Overtime Score
count,1277.000000,1277.000000,1277.000000,145.000000,1277.000000,1277.000000,1277.000000,145.000000
mean,10.719655,6.068912,4.441660,1.751724,10.417384,4.265466,5.921691,1.986207
std,3.377692,2.400029,2.327245,1.876503,3.634403,2.368982,2.399740,1.825689
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,4.000000,3.000000,0.000000,8.000000,3.000000,4.000000,0.000000
50%,13.000000,6.000000,4.000000,2.000000,13.000000,4.000000,6.000000,2.000000
75%,13.000000,8.000000,6.000000,2.000000,13.000000,6.000000,8.000000,3.000000
max,25.000000,12.000000,11.000000,13.000000,23.000000,11.000000,12.000000,11.000000

Tournament                  0
Stage                       0
Match Type                  0
Match Name                  0
Map                         0
Team A                      0
Team A Score                0
Team A Attacker Score       0
Team A Defender Score       0
Team A Overtime Score    1132
Team B                      0
Team B Score                0
Team B Attacker Score       0
Team B Defender Score       0
Team B Overtime Score    1132
Duration                   98
dtype: int64

Дубликатов: 0

In [10]:
df = df.replace('Mega Minors', 'NRG') # ошибка в исходных данных: NRG записана как Mega Minors
df.drop('Duration', axis = 1, inplace = True) # удаляем признак: есть пропуски и для вопроса не нужен
df[['Team A Overtime Score', 'Team B Overtime Score']] = df[['Team A Overtime Score', 'Team B Overtime Score']].fillna(0) # нет овертайма -> 0
df = df.sort_values(by = 'Tournament')
df = df.drop_duplicates()
display(df.head())
print(df.shape)
df.to_csv('../datasets/processed/maps_scores.csv')

,Tournament,Stage,Match Type,Match Name,Map,Team A,Team A Score,Team A Attacker Score,Team A Defender Score,Team A Overtime Score,Team B,Team B Score,Team B Attacker Score,Team B Defender Score,Team B Overtime Score
1165,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,Evil Geniuses vs LOUD,Split,Evil Geniuses,12,8,4,0.0,LOUD,14,8,4,2.0
1166,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,Evil Geniuses vs LOUD,Pearl,Evil Geniuses,10,6,4,0.0,LOUD,13,7,6,0.0
1167,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,MIBR vs 100 Thieves,Lotus,MIBR,4,2,2,0.0,100 Thieves,13,3,10,0.0
1168,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,MIBR vs 100 Thieves,Bind,MIBR,9,8,1,0.0,100 Thieves,13,9,4,0.0
1169,VCT 2025: Americas Kickoff,Main Event,Upper Round 1,2Game Esports vs FURIA,Haven,2Game Esports,7,5,2,0.0,FURIA,13,6,7,0.0

(1277, 15)

<p>Процент побед FNATIC на каждой карте за сезон</p>

In [11]:
fm = df[(df['Team A'] == 'FNATIC') | (df['Team B'] == 'FNATIC')].copy()
fm['FNATIC Score'] = np.where(fm['Team A'] == 'FNATIC', fm['Team A Score'], fm['Team B Score'])
fm['Opponent Score'] = np.where(fm['Team A'] == 'FNATIC', fm['Team B Score'], fm['Team A Score'])
fm['Win'] = fm['FNATIC Score'] > fm['Opponent Score']
map_stats = fm.groupby('Map')['Win'].agg(['sum', 'count'])
map_stats.columns = ['Побед', 'Сыграно']
map_stats['% побед'] = (map_stats['Побед'] / map_stats['Сыграно'] * 100).round(1)
display(map_stats.sort_values(by = '% побед'))

          Побед  Сыграно  % побед
Map
Sunset        0        6      0.0
Ascent        6       12     50.0
Pearl         1        2     50.0
Abyss         4        7     57.1
Lotus         9       15     60.0
Haven         8       13     61.5
Bind          5        8     62.5
Corrode       3        4     75.0
Fracture      6        8     75.0
Split         8       10     80.0
Icebox        7        8     87.5

<p>Карты в проигранных гранд-финалах</p>

In [12]:
gf_maps = fm[(fm['Match Type'] == 'Grand Final') & fm['Tournament'].isin(lost)]
display(gf_maps[['Tournament', 'Map', 'FNATIC Score', 'Opponent Score', 'Win']])

,Tournament,Map,FNATIC Score,Opponent Score,Win
83,Valorant Champions 2025,Corrode,3,13,False
84,Valorant Champions 2025,Lotus,6,13,False
85,Valorant Champions 2025,Abyss,15,13,True
86,Valorant Champions 2025,Ascent,13,8,True
87,Valorant Champions 2025,Sunset,5,13,False
575,Valorant Masters Toronto 2025,Sunset,11,13,False
576,Valorant Masters Toronto 2025,Icebox,17,15,True
577,Valorant Masters Toronto 2025,Pearl,10,13,False
578,Valorant Masters Toronto 2025,Lotus,12,14,False

<p><b>Ответ:</b></p>
<ul>
    <li>Сильные карты FNATIC — Split и Icebox, слабые — Sunset, Ascent и Pearl.</li>
    <li>Sunset и Lotus были в обоих проигранных финалах и оба раза закончились поражением.</li>
</ul>

<h2>Файл: overview.csv — игроки FNATIC</h2>
<p>Основная статистика игрока на карте.</p>
<ul>
    <li><code>Tournament</code>, <code>Stage</code>, <code>Match Type</code>, <code>Match Name</code>, <code>Map</code>, <code>Player</code>, <code>Team</code> — турнир, стадия, тип матча, матч, карта, игрок, команда;</li>
    <li><code>Agents</code> — агент;</li>
    <li><code>Rating</code> — рейтинг игрока;</li>
    <li><code>Average Combat Score</code> (ACS) — средний боевой счёт за раунд;</li>
    <li><code>Kills</code>, <code>Deaths</code>, <code>Assists</code> — убийства, смерти, помощь;</li>
    <li><code>Kills - Deaths (KD)</code> — разница убийств и смертей;</li>
    <li><code>Kill, Assist, Trade, Survive %</code> (KAST) — процент раундов, где игрок убил, помог, был «разменян» или выжил;</li>
    <li><code>Average Damage Per Round</code> (ADR) — средний урон за раунд;</li>
    <li><code>Headshot %</code> — процент попаданий в голову;</li>
    <li><code>First Kills</code>, <code>First Deaths</code>, <code>Kills - Deaths (FKD)</code> — первые убийства и смерти в раунде и их разница;</li>
    <li><code>Side</code> — сторона: <code>both</code> (итог), <code>attack</code>, <code>defend</code>.</li>
</ul>

In [13]:
path = '../datasets/archive/vct_2025/matches/overview.csv'
df = pd.read_csv(path)
df.info()
display(df.head())
print(df.shape)
print(df.shape[0]) # 0 - это строки
print(df.shape[1]) # 1 - это столбцы
display(df.describe())
display(df.isnull().sum())
print('Дубликатов:', df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 53226 entries, 0 to 53225
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Tournament                      53226 non-null  str
 1   Stage                           53226 non-null  str
 2   Match Type                      53226 non-null  str
 3   Match Name                      53226 non-null  str
 4   Map                             53226 non-null  str
 5   Player                          53226 non-null  str
 6   Team                            53226 non-null  str
 7   Agents                          53226 non-null  str
 8   Rating                          49146 non-null  float64
 9   Average Combat Score            50481 non-null  float64
 10  Kills                           50676 non-null  float64
 11  Deaths                          50676 non-null  float64
 12  Assists                         50676 non-null  float64
 13  Kills - Deaths (KD)             50670 non-null  float64
 14  Kill, Assist, Trade, Survive %  49344 non-null  str
 15  Average Damage Per Round        49170 non-null  float64
 16  Headshot %                      49377 non-null  str
 17  First Kills                     49266 non-null  float64
 18  First Deaths                    49269 non-null  float64
 19  Kills - Deaths (FKD)            49269 non-null  float64
 20  Side                            53226 non-null  str
dtypes: float64(10), str(11)
memory usage: 14.0 MB

,Tournament,Stage,Match Type,Match Name,Map,Player,Team,Agents,Rating,Average Combat Score,...,Deaths,Assists,Kills - Deaths (KD),"Kill, Assist, Trade, Survive %",Average Damage Per Round,Headshot %,First Kills,First Deaths,Kills - Deaths (FKD),Side
0,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,something,Paper Rex,yoru,1.63,258.0,...,12.0,12.0,9.0,91%,167.0,15%,4.0,0.0,4.0,both
1,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,something,Paper Rex,yoru,1.33,199.0,...,5.0,6.0,2.0,100%,137.0,16%,1.0,0.0,1.0,attack
2,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,something,Paper Rex,yoru,1.88,308.0,...,7.0,6.0,7.0,83%,192.0,13%,3.0,0.0,3.0,defend
3,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,Jinggg,Paper Rex,raze,1.52,315.0,...,14.0,7.0,10.0,82%,207.0,18%,5.0,2.0,3.0,both
4,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,Jinggg,Paper Rex,raze,1.11,239.0,...,7.0,2.0,1.0,80%,148.0,13%,3.0,2.0,1.0,attack

(53226, 21)
53226
21

,Rating,Average Combat Score,Kills,Deaths,Assists,Kills - Deaths (KD),Average Damage Per Round,First Kills,First Deaths,Kills - Deaths (FKD)
count,49146.000000,50481.000000,50676.000000,50676.000000,50676.000000,50670.000000,49170.000000,49266.000000,49269.000000,49269.000000
mean,0.997202,196.580416,14.170732,14.183519,5.778593,-0.012789,128.554017,2.022165,2.022448,-0.000406
std,0.392257,67.693251,11.019069,10.293038,5.437769,6.070939,42.583618,2.284085,2.220077,2.150975
min,0.010000,-1.000000,-1.000000,0.000000,0.000000,-35.000000,0.000000,0.000000,0.000000,-15.000000
25%,0.740000,152.000000,7.000000,8.000000,2.000000,-4.000000,100.000000,0.000000,1.000000,-1.000000
50%,0.980000,192.000000,11.000000,11.000000,4.000000,0.000000,126.000000,1.000000,1.000000,0.000000
75%,1.230000,236.000000,18.000000,17.000000,8.000000,4.000000,153.000000,3.000000,3.000000,1.000000
max,4.230000,778.000000,103.000000,97.000000,80.000000,46.000000,503.000000,26.000000,26.000000,14.000000

Tournament                           0
Stage                                0
Match Type                           0
Match Name                           0
Map                                  0
Player                               0
Team                                 0
Agents                               0
Rating                            4080
Average Combat Score              2745
Kills                             2550
Deaths                            2550
Assists                           2550
Kills - Deaths (KD)               2556
Kill, Assist, Trade, Survive %    3882
Average Damage Per Round          4056
Headshot %                        3849
First Kills                       3960
First Deaths                      3957
Kills - Deaths (FKD)              3957
Side                                 0
dtype: int64

Дубликатов: 0

In [14]:
df = df.replace('Mega Minors', 'NRG') # ошибка в исходных данных: NRG записана как Mega Minors
df = df[df['Side'] == 'both'] # оставляем итог по обеим сторонам, attack / defend удаляем
df.drop(['Side', 'Kills - Deaths (KD)', 'Kills - Deaths (FKD)'], axis = 1, inplace = True) # KD и FKD считаются из других столбцов
df['Kill, Assist, Trade, Survive %'] = df['Kill, Assist, Trade, Survive %'].str.replace('%', '').astype(float)
df['Headshot %'] = df['Headshot %'].str.replace('%', '').astype(float)
df = df[df['Map'] != 'All Maps'] # удаляем строки-итоги по всем картам
df = df.dropna()
df = df.sort_values(by = 'Rating', ascending = False)
df = df.drop_duplicates()
display(df.head())
print(df.shape)
df.to_csv('../datasets/processed/overview.csv')

,Tournament,Stage,Match Type,Match Name,Map,Player,Team,Agents,Rating,Average Combat Score,Kills,Deaths,Assists,"Kill, Assist, Trade, Survive %",Average Damage Per Round,Headshot %,First Kills,First Deaths
25656,VCT 2025: EMEA Stage 1,Group Stage,Week 3,Natus Vincere vs GIANTX,Split,hiro,Natus Vincere,vyse,2.66,397.0,22.0,2.0,7.0,100.0,262.0,26.0,1.0,0.0
26301,VCT 2025: EMEA Stage 1,Group Stage,Week 4,Gentle Mates vs BBL Esports,Haven,sociablEE,BBL Esports,sova,2.61,421.0,26.0,4.0,7.0,93.0,282.0,38.0,2.0,0.0
21090,VCT 2025: China Stage 2,Playoffs,Lower Round 2,Xi Lai Gaming vs All Gamers,Lotus,Rarga,Xi Lai Gaming,sage,2.54,452.0,23.0,4.0,12.0,93.0,247.0,29.0,2.0,0.0
28416,VCT 2025: EMEA Stage 1,Playoffs,Grand Final,FNATIC vs Team Heretics,Split,kaajak,FNATIC,yoru,2.47,419.0,28.0,5.0,2.0,94.0,272.0,43.0,4.0,2.0
38976,VCT 2025: Americas Stage 1,Group Stage,Week 3,G2 Esports vs NRG,Lotus,jawgemo,G2 Esports,yoru,2.46,460.0,27.0,7.0,5.0,100.0,294.0,30.0,2.0,1.0

(11760, 18)

<p>Количество записей по командам (целевая переменная Team)</p>

In [15]:
display(df['Team'].value_counts().head(10))

Team
G2 Esports        500
FNATIC            465
Team Liquid       460
T1                435
Paper Rex         420
Sentinels         420
Rex Regum Qeon    420
DRX               400
MIBR              350
NRG               330
Name: count, dtype: int64

<p>Средняя статистика игроков FNATIC: весь сезон и проигранные гранд-финалы</p>

In [16]:
cols = ['Rating', 'Average Combat Score', 'Kills', 'Deaths', 'Average Damage Per Round', 'First Kills', 'First Deaths']
fnc = df[df['Team'] == 'FNATIC']
fnc_gf = fnc[(fnc['Match Type'] == 'Grand Final') & fnc['Tournament'].isin(lost)]
display(pd.DataFrame({'Весь сезон': fnc[cols].mean(), 'Проигранные гранд-финалы': fnc_gf[cols].mean()}).round(2))

                          Весь сезон  Проигранные гранд-финалы
Rating                          1.04                      0.93
Average Combat Score          199.40                    187.00
Kills                          15.34                     15.16
Deaths                         14.37                     16.36
Average Damage Per Round      132.52                    124.07
First Kills                     2.32                      2.42
First Deaths                    2.03                      2.18

<p>Игроки FNATIC в проигранных гранд-финалах</p>

In [17]:
display(fnc_gf.groupby('Player')[cols].mean().round(2).sort_values(by = 'Rating', ascending = False))

,Rating,Average Combat Score,Kills,Deaths,Average Damage Per Round,First Kills,First Deaths
Player,,,,,,,
kaajak,1.06,223.78,19.00,17.22,144.44,5.00,3.11
Alfajer,1.04,231.67,19.00,17.11,151.89,3.33,2.33
Chronicle,0.98,185.89,15.67,15.67,125.00,1.33,1.56
crashies,0.87,166.33,13.33,15.78,114.56,1.22,1.78
Boaster,0.69,127.33,8.78,16.00,84.44,1.22,2.11

<p><b>Ответ:</b></p>
<ul>
    <li>В проигранных финалах упали все показатели команды.</li>
</ul>

<h2>Файл: win_loss_methods_round_number.csv — раунды FNATIC</h2>
<p>Исход и способ окончания каждого раунда.</p>
<ul>
    <li><code>Tournament</code>, <code>Stage</code>, <code>Match Type</code>, <code>Match Name</code>, <code>Map</code>, <code>Round Number</code> — турнир, стадия, тип матча, матч, карта, номер раунда;</li>
    <li><code>Team</code> — команда;</li>
    <li><code>Method</code> — способ окончания раунда: <code>Elimination</code> / <code>Eliminated</code> (убили всех / всех убили), <code>Detonated</code> (взрыв спайка), <code>Defused</code> (спайк обезврежен), <code>Time Expiry</code> (вышло время) и противоположные им для проигравшей стороны;</li>
    <li><code>Outcome</code> — исход раунда (Win / Loss).</li>
</ul>

In [18]:
path = '../datasets/archive/vct_2025/matches/win_loss_methods_round_number.csv'
df = pd.read_csv(path)
df.info()
display(df.head())
print(df.shape)
print(df.shape[0]) # 0 - это строки
print(df.shape[1]) # 1 - это столбцы
display(df.describe())
display(df.isnull().sum())
print('Дубликатов:', df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 53950 entries, 0 to 53949
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tournament    53950 non-null  str
 1   Stage         53950 non-null  str
 2   Match Type    53950 non-null  str
 3   Match Name    53950 non-null  str
 4   Map           53950 non-null  str
 5   Round Number  53950 non-null  int64
 6   Team          53950 non-null  str
 7   Method        53950 non-null  str
 8   Outcome       53950 non-null  str
dtypes: int64(1), str(8)
memory usage: 8.8 MB

,Tournament,Stage,Match Type,Match Name,Map,Round Number,Team,Method,Outcome
0,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,1,Xi Lai Gaming,Elimination,Win
1,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,1,Paper Rex,Eliminated,Loss
2,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,2,Xi Lai Gaming,Detonated,Win
3,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,2,Paper Rex,Failed Defused,Loss
4,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,3,Paper Rex,Defused,Win

(53950, 9)
53950
9

       Round Number
count  53950.000000
mean      11.385431
std        6.660956
min        1.000000
25%        6.000000
50%       11.000000
75%       16.000000
max       48.000000

Tournament      0
Stage           0
Match Type      0
Match Name      0
Map             0
Round Number    0
Team            0
Method          0
Outcome         0
dtype: int64

Дубликатов: 0

In [19]:
df = df.replace('Mega Minors', 'NRG') # ошибка в исходных данных: NRG записана как Mega Minors
df = df.sort_values(by = 'Round Number')
df = df.drop_duplicates()
display(df.head())
print(df.shape)
df.to_csv('../datasets/processed/win_loss_methods_round_number.csv')

,Tournament,Stage,Match Type,Match Name,Map,Round Number,Team,Method,Outcome
42244,Valorant Masters Bangkok 2025,Swiss Stage,Round 1,EDward Gaming vs Team Liquid,Pearl,1,Team Liquid,Defused,Win
42245,Valorant Masters Bangkok 2025,Swiss Stage,Round 1,EDward Gaming vs Team Liquid,Pearl,1,EDward Gaming,Detonated Denied,Loss
5178,VCT 2025: Americas Stage 2,Group Stage,Week 3,Sentinels vs Cloud9,Lotus,1,Sentinels,Defused,Win
5179,VCT 2025: Americas Stage 2,Group Stage,Week 3,Sentinels vs Cloud9,Lotus,1,Cloud9,Detonated Denied,Loss
35716,VCT 2025: China Stage 1,Group Stage,Week 4,Trace Esports vs Xi Lai Gaming,Lotus,1,Xi Lai Gaming,Defused,Win

(53950, 9)

<p>Способы окончания раундов FNATIC: весь сезон и проигранные финалы</p>

In [20]:
fwl = df[df['Team'] == 'FNATIC']
gf_wl = fwl[(fwl['Match Type'] == 'Grand Final') & fwl['Tournament'].isin(lost)]
display(pd.DataFrame({
    'Весь сезон, %': (fwl['Method'].value_counts(normalize = True) * 100).round(1),
    'Проигранные финалы, %': (gf_wl['Method'].value_counts(normalize = True) * 100).round(1)}))

                               Весь сезон, %  Проигранные финалы, %
Method
Defused                                 12.0                   13.0
Detonated                                6.5                    3.9
Detonated Denied                         7.9                    9.7
Eliminated                              29.0                   39.1
Elimination                             33.3                   26.6
Failed Defused                           6.6                    5.3
Time Expiry (Failed to Plant)            3.7                    1.4
Time Expiry (No Plant)                   1.0                    1.0

<p>Пистолетные раунды (1-й и 13-й)</p>

In [21]:
pistols = fwl[fwl['Round Number'].isin([1, 13])]
gf_pistols = gf_wl[gf_wl['Round Number'].isin([1, 13])]
print('Пистолетные раунды за сезон, % побед:', round((pistols['Outcome'] == 'Win').mean() * 100, 1))
print('Пистолетные раунды в проигранных финалах, % побед:', round((gf_pistols['Outcome'] == 'Win').mean() * 100, 1))

Пистолетные раунды за сезон, % побед: 54.3
Пистолетные раунды в проигранных финалах, % побед: 66.7

<p><b>Ответ:</b></p>
<ul>
    <li>Раунды проигрывались в индивидуальных перестрелках.</li>
</ul>

<h2>Файл: eco_rounds.csv — экономика FNATIC</h2>
<p>Экономика каждого раунда.</p>
<ul>
    <li><code>Tournament</code>, <code>Stage</code>, <code>Match Type</code>, <code>Match Name</code>, <code>Map</code> — турнир, стадия, тип матча, матч, карта;</li>
    <li><code>Round Number</code> — номер раунда;</li>
    <li><code>Team</code> — команда;</li>
    <li><code>Loadout Value</code> — стоимость снаряжения команды;</li>
    <li><code>Remaining Credits</code> — оставшиеся кредиты;</li>
    <li><code>Type</code> — тип закупки (эко, полу-эко, полу-закупка, полная закупка);</li>
    <li><code>Outcome</code> — исход раунда (Win / Loss).</li>
</ul>
<p>В этом файле нет данных по Champions 2025, поэтому экономику финала смотрим только для Masters Toronto. У Masters Toronto не заполнена стоимость снаряжения (<code>Loadout Value</code>), но тип закупки (<code>Type</code>) есть, поэтому эти строки оставляем.</p>

In [22]:
path = '../datasets/archive/vct_2025/matches/eco_rounds.csv'
df = pd.read_csv(path)
df.info()
display(df.head())
print(df.shape)
print(df.shape[0]) # 0 - это строки
print(df.shape[1]) # 1 - это столбцы
display(df.describe())
display(df.isnull().sum())
print('Дубликатов:', df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 25182 entries, 0 to 25181
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tournament         25182 non-null  str
 1   Stage              25182 non-null  str
 2   Match Type         25182 non-null  str
 3   Match Name         25182 non-null  str
 4   Map                25182 non-null  str
 5   Round Number       25182 non-null  int64
 6   Team               25182 non-null  str
 7   Loadout Value      22632 non-null  str
 8   Remaining Credits  25182 non-null  str
 9   Type               25182 non-null  str
 10  Outcome            25182 non-null  str
dtypes: int64(1), str(10)
memory usage: 5.0 MB

,Tournament,Stage,Match Type,Match Name,Map,Round Number,Team,Loadout Value,Remaining Credits,Type,Outcome
0,Valorant Masters Toronto 2025,Swiss Stage,Round 1,Team Heretics vs Paper Rex,Pearl,1,Team Heretics,NaN,0.2k,Eco: 0-5k,Loss
1,Valorant Masters Toronto 2025,Swiss Stage,Round 1,Team Heretics vs Paper Rex,Pearl,1,Paper Rex,NaN,0.5k,Eco: 0-5k,Win
2,Valorant Masters Toronto 2025,Swiss Stage,Round 1,Team Heretics vs Paper Rex,Pearl,2,Team Heretics,NaN,10.2k,Eco: 0-5k,Loss
3,Valorant Masters Toronto 2025,Swiss Stage,Round 1,Team Heretics vs Paper Rex,Pearl,2,Paper Rex,NaN,2.3k,Semi-buy: 10-20k,Win
4,Valorant Masters Toronto 2025,Swiss Stage,Round 1,Team Heretics vs Paper Rex,Pearl,3,Team Heretics,NaN,0.2k,Full buy: 20k+,Win

(25182, 11)
25182
11

       Round Number
count  25182.000000
mean      11.470971
std        6.788850
min        1.000000
25%        6.000000
50%       11.000000
75%       16.000000
max       48.000000

Tournament              0
Stage                   0
Match Type              0
Match Name              0
Map                     0
Round Number            0
Team                    0
Loadout Value        2550
Remaining Credits       0
Type                    0
Outcome                 0
dtype: int64

Дубликатов: 0

In [23]:
df = df.replace('Mega Minors', 'NRG') # ошибка в исходных данных: NRG записана как Mega Minors
df['Loadout Value'] = df['Loadout Value'].str.replace('k', '').astype(float) * 1000 # '24.3k' -> 24300
df['Remaining Credits'] = df['Remaining Credits'].str.replace('k', '').astype(float) * 1000
# пропуски в Loadout Value не удаляем: это весь Masters Toronto, а тип закупки (Type) для него есть
df = df.sort_values(by = 'Round Number')
df = df.drop_duplicates()
display(df.head())
print(df.shape)
df.to_csv('../datasets/processed/eco_rounds.csv')

,Tournament,Stage,Match Type,Match Name,Map,Round Number,Team,Loadout Value,Remaining Credits,Type,Outcome
17715,Champions Tour 2025: EMEA Kickoff,Main Event,Upper Round 1,BBL Esports vs GIANTX,Pearl,1,GIANTX,3400.0,300.0,Eco: 0-5k,Loss
17714,Champions Tour 2025: EMEA Kickoff,Main Event,Upper Round 1,BBL Esports vs GIANTX,Pearl,1,BBL Esports,4200.0,100.0,Eco: 0-5k,Win
17751,Champions Tour 2025: EMEA Kickoff,Main Event,Upper Round 1,Karmine Corp vs Natus Vincere,Abyss,1,Natus Vincere,3600.0,300.0,Eco: 0-5k,Loss
17750,Champions Tour 2025: EMEA Kickoff,Main Event,Upper Round 1,Karmine Corp vs Natus Vincere,Abyss,1,Karmine Corp,3800.0,200.0,Eco: 0-5k,Win
73,Valorant Masters Toronto 2025,Swiss Stage,Round 1,Bilibili Gaming vs Team Liquid,Icebox,1,Team Liquid,NaN,200.0,Eco: 0-5k,Loss

(25182, 11)

<p>Процент побед по типу закупки: FNATIC за сезон, FNATIC и Paper Rex в финале Masters Toronto</p>

In [24]:
gf_eco = df[(df['Tournament'] == 'Valorant Masters Toronto 2025') & (df['Match Type'] == 'Grand Final')]
season_eco = df[df['Team'] == 'FNATIC']
display(pd.DataFrame({
    'FNATIC за сезон, % побед': season_eco.groupby('Type')['Outcome'].apply(lambda s: (s == 'Win').mean() * 100).round(1),
    'FNATIC в финале, % побед': gf_eco[gf_eco['Team'] == 'FNATIC'].groupby('Type')['Outcome'].apply(lambda s: (s == 'Win').mean() * 100).round(1),
    'Paper Rex в финале, % побед': gf_eco[gf_eco['Team'] == 'Paper Rex'].groupby('Type')['Outcome'].apply(lambda s: (s == 'Win').mean() * 100).round(1)}))

,"FNATIC за сезон, % побед","FNATIC в финале, % побед","Paper Rex в финале, % побед"
Type,,,
Eco: 0-5k,39.6,66.7,14.3
Full buy: 20k+,60.0,49.3,65.3
Semi-buy: 10-20k,52.5,40.0,37.5
Semi-eco: 5-10k,25.6,25.0,0.0

<p><b>Ответ:</b></p>
<ul>
    <li>У команды были достаточно хорошие эко-раунды: показатель очень высокий (66,7% побед).</li>
</ul>

<h2>Итог по личной цели</h2>
<p>В своём регионе FNATIC доминировали: победа на одном из этапов EMEA гарантировала им попадание на Champions. Но средний мап-пул и неудачное для команды обновление пула карт дали свои плоды. В финалах команда выступала хуже обычного по индивидуальным показателям.</p>

<p>Вывод: провели разведочный анализ данных по датасету.</p>